### ISSUE TITLE
Buildings menu move when the player drag the block

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#101]
Lorsqu'on déplace un bloc à partir de l'UI, le menu se déplace en fonction de la souris. Le menu ne devrait pas bouger lorsque le joueur déplace un bloc.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/108/commits/28ddedc15fb981eeaaf34a5e95dbf75e73c94ee2
