### ISSUE TITLE
Limit tower

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#102]
https://gyazo.com/596a0b1b8263589f29ed5027d65db967

Le jeu rame énormément et le haut de la tour n'est pas visible.

On peut laisser ça comme ça mais ca peut poser des problèmes de performances.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/108/commits/e4e120e7166e3064ba838cb478968f4fe149169f
