### ISSUE TITLE
Can't build above a building with a carton box

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#120]
Lorsque le joueur veut placer un bâtiment en carton sur un autre, il ne peut pas.
https://gyazo.com/bbd9d25614f2bb4a6f7b68c608ac66d9
Il faudrait que le joueur puisse déplacer un bâtiment sur un autre, peu importe son état.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/139/commits/53de60f50cd83be309e638f9de1401b425742dac
