### ISSUE TITLE
Pick a block and mouse hover the block menu grab multi blocks

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#121]
https://gyazo.com/017c269f91ca4d7419b1c85627d81dea

Quand on prend un block et qu'on déplace la souris en maintenant le clique, le joueur peut récupérer plusieurs blocs dans les différents menus.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/139/commits/6106fb229a939cc9269f7e808fe02d1994a66e9a
