### ISSUE TITLE
The spatioport can be built upon

### ISSUE THREAD

**Issue by Rackover** [Rackover/Stackolony#136]
[2019-02-22_15-26-15.zip](https://github.com/Rackover/Stackolony/files/2894427/2019-02-22_15-26-15.zip)

It is possible to build on the spatioport by using other blocks

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/139/commits/70d3a28174ce60fe747850ad3a77dea8f5fa535f
