### ISSUE TITLE
Destroy the block directly from the menu

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#137]
Lorsque le joueur sélectionne le mauvais block dans le menu, il est obligé de le placer dans le monde puis de le détruire.

Enhancement (plusieurs possibilités) : 
Un clic droit pendant le drag d'un objet permet de le détruire
Pouvoir jeter à la poubelle un block qui provient directement du menu

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/139/commits/0ab4492919ca0cd9351377ddcb0ebbdf4c7fa2ad
