### ISSUE TITLE
superposable blocks

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#140]
https://gyazo.com/23f8673d5dc7a987ec13a5b705e660de

Lorsque deux blocs sont l'un sur l'autre et que celui du bas est envoyé à la poubelle, le joueur peut superposer un bloc sur celui qui est désormais seul.

**Comment by INoobody** [comment]
https://gyazo.com/f548392156caa19c03aebf5c4a3bf4ab Pareil lorsque la base d'une tour est mise à la poubelle.

**Comment by Marolles** [comment]
Impossible de reproduire le bug dans la derniere version, je pars du principe que c'est reglé du coup
