### ISSUE TITLE
After destroying a block, the bridge mode don't work

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#141]
https://gyazo.com/4c9ff6534705a02a2066357485d966eb

Le bridge mode ne fonctionne plus après avoir placé un block dans la corbeille. Le dernier block sélectionné est téléporté à la main du joueur lorsqu'il veut placer un nouveau block.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/161/commits/3d052a090fcf2d40856b6d193f4c57c4558ea2b9
