### ISSUE TITLE
Spatioport destroyed when he is dragged in an error

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#142]
https://gyazo.com/8d1abf02f107aa76ae6edb43e5d7a47f

Le spatioport disparait si on le drag and drog sur une mine/nest/eau.

**Comment by INoobody** [comment]
Même faire un clic droit lors d'un déplacement du spatioport le supprime.

**Comment by Marolles** [comment]
Déjà fixé, je ferme
