### ISSUE TITLE
Blocks freeze when drag and bridge 

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#154]
https://gyazo.com/19cdaee79c667d0562434bfb82525c23

Le joueur peut faire freeze des blocs en faisant rapidement des drag and drop tout en spammant le clic droit.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/161/commits/5573975e136f2a2b0a85e652e9360daf70e2d26a
