### ISSUE TITLE
All the city return to carton when the spread is difficult

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#157]
https://gyazo.com/6e27a5a8aada6b7964905ec6494d62d0

Lorsque le joueur place un bloc (généralement energy), toute la ville se remet en carton pour se remet normalement.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/161/commits/0055803d9ff9b07a8b186674f2b656b1d6e128d2
