### ISSUE TITLE
We can move nests and mines

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#181]
https://gyazo.com/ef6cf350e95144a77a468c039c6890e6

Lorsque le joueur fait un clique droit puis un clique gauche sur un nid ou une mine, le joueur peut les déplacer, ce qui n'est normalement pas possible.

**Comment by INoobody** [comment]
Le joueur ne peut plus faire de ponts ensuite sur ces blocs.

**Comment by INoobody** [comment]
Ce bug ressemble fortement au bug qu'il y avait lorsqu'on cliquait sur shift pour faire des ponts sur les blocs et que ces blocs se figeait.

**Comment by Rackover** [comment]
oui c'est le bug des blocks fantômes, je sais pas trop à quoi il est dû

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/197/commits/9a786f4f3ce865979fba0a048d89adeb9b5ea028
