### ISSUE TITLE
Player can put a block "in" a mine

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#183]
https://gyazo.com/0a8b6ceb40bbcd1c6c2827d8f59abc8d

Le joueur peut placer un bloc à l'intérieur d'une mine (pas au dessus), ce qui n'est normalement pas possible.

**Comment by INoobody** [comment]
https://gyazo.com/cbfdd5f9f36308547c1bf223dc6b554d Le bloc semble être en "attente" d'être placé.

**Comment by INoobody** [comment]
https://gyazo.com/c822e07a96988cc711c40520e94c36c1 La console, si ca peut aider

**Comment by Marolles** [comment]
Il peut aussi placer en dessous de la mine, dans ce cas le bloc remonte et se place au dessus de la mine, sans causer d'erreur

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/197/commits/0022df9839b36d4103ccf0468c35525a6967cbf3
