### ISSUE TITLE
Tooltip too long

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#192]
![image](https://user-images.githubusercontent.com/23194499/53302523-2aa4c200-385f-11e9-9d3e-583a7a356dc1.png)

**Comment by INoobody** [comment]
La tooltip du block Barrack est trop grande.

**Comment by Barkintosh** [comment]
Go raccourcir le texte, mais je vais quand même réduire un poil la taille de la font

**Comment by Barkintosh** [comment]
![image](https://user-images.githubusercontent.com/28601638/53303605-c983eb00-386c-11e9-9ac3-d47dc75d9c0a.png)

**Comment by Barkintosh** [comment]
Içi, celui qui maitrise le prefab d'interface
