### ISSUE TITLE
Spaceport not providing Electricity

### ISSUE THREAD

**Issue by Nohensen** [Rackover/Stackolony#61]
le feedback de besoin éléctrique apparait sur le premier block connécté au spatioport
Le spatioport ne transmet donc pas d'electricité
je me demande s'il transmet de la nourriture?

**Comment by Rackover** [comment]
faut rajouter le flag d'emetteur de courant sur le spreadsheet CSV des blocks
https://docs.google.com/spreadsheets/d/1IT_QpBYv5SL0FIr_zf58u5FydG1OQ0BP2hMRhr3Qk7A/edit#gid=0

**Comment by INoobody** [comment]
En exportant le CSV que j'ai mis sur Discord (ou en DL Blocks) normalement c'est bon !

**Comment by Barkintosh** [comment]
Si c'est bon et c'est sur master, tu peux close l'**issue** avec le bouton **Close and comment**
