### ISSUE TITLE
No Overlay Icons

### ISSUE THREAD

**Issue by Nohensen** [Rackover/Stackolony#63]
Certains overlays n'ont pas d'icone:
_Fire risk
_No Overlay
_Food Consuption
_Density
_[LOC:OVERLAY:TYPE] ??

**Comment by Barkintosh** [comment]
![capture](https://user-images.githubusercontent.com/28601638/52542983-9b4ed780-2da5-11e9-944b-8d1a93fc2a34.PNG)

**Comment by Barkintosh** [comment]
Si on les a faut juste les Drags and drop içi.
