### ISSUE TITLE
Block package opens without being connected to the Spaceport

### ISSUE THREAD

**Issue by Nohensen** [Rackover/Stackolony#67]
Après avoir passé le tuto sans placer aucun block
en essayant de poser un block le jour 11, son package s'ouvre sans qu'il soit connecté au spatioport

Probleme rencontré 1 fois
j'essaie de le reproduire plus en détail, mais jcp

**Comment by Rackover** [comment]
Lié au crash de mission, probablement reglé, à rouvrir si le bug reparaît
