### ISSUE TITLE
Riots in wrong blocks

### ISSUE THREAD

**Issue by Nohensen** [Rackover/Stackolony#68]
Le spatioport, les mines et les nids peuvent etre atteints par les emeutes dans le proto
je n'ai construit aucun block durant le tuto, et c'est eux qui sont atteints

**Comment by Barkintosh** [comment]
ça marche, je crée un boolean RiotProof qui protège un Block des émeutes ( à setté dans les blockschemes à la main vu que y'en très peu comme ça (3))
