### ISSUE TITLE
Click on the Mess building create a tons of building

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#85]
Lorsqu'on clique sur le bâtiment de nourriture dans l'ui, pleins de bâtiments pop à côté du spatioport. Les blocs créés sont tous au même endroit. Quand on laisse le clique de la souris, ca spam les blocs.

https://gyazo.com/9cf6bc805edb57969c0b0381f2128b7f

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/108/commits/49e0b1460f5ae0485551886777d7dea95ff2073b
