### ISSUE TITLE
Grab a block through a event/citizen drag&drop

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#87]
On peut grab un bloc quand on veut bouger une fenêtre comme les évènements ou le système de classement des habitants. De plus, le mouse hover fonctionne aussi sur les bâtiments lorsqu'il y a une fenêtre par dessus.
Normalement le joueur ne devrait pas pouvoir interagir avec les blocs cachés par l'ui.

**Comment by Barkintosh** [comment]
EventSystems.EventSystem.IsPointerOverGameObject

Ajouter cet method boolean dans pas mal de raycast
