### ISSUE TITLE
We can't drop a block taken from the menu

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#88]
Lorsqu'un bloc est pris du menu et que le joueur veut le remettre dans le menu (car il a pris le mauvais, par exemple), le bloc se place sur la scène, derrière le menu déroulant.
Normalement, le bloc ne se passe pas dans le monde si il est drop dans le menu déroulant des bâtiments.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/139/commits/0ab4492919ca0cd9351377ddcb0ebbdf4c7fa2ad
