### ISSUE TITLE
Recreate props when they are destroyed

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#90]
Lorsqu'on place un bloc sur un prop (arbres par exemple), il disparait. Mais lorsqu'on enlève le bloc l'arbre ne réapparait pas. Le joueur peut donc enlever tous les props de la map en plaçant des blocs dessus et en les enlevant.
Ce serait bien que les props réapparaissent si les blocs qui les ont enlevés ne sont plus sur la case.

**Comment by Marolles** [comment]
Après discussion on avait décidé que les props restaient détruit pour toujours, pour bien insister sur le fait que le joueur "colonise" la planète en détruisant ses ressources naturelles. Si tu es contre l'idée on peut en discuter en réunion

**Comment by INoobody** [comment]
Ah c'est une bonne idée :)
