### ISSUE TITLE
Right and left click at the same time in a block in the menu break the others blocks

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#91]
(Voir le gif pour plus de compréhension : https://gyazo.com/ddfb1ba982f0d85cc81249be833b1266 )

Quand on clique gauche et droite sur un bâtiment dans le menu déroulant et qu'on maintient les touches, à un moment la ville pète un câble, les bâtiments se remettent dans leur boite et s'enlève très rapidement, l'électricité ne semble plus circuler.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/108/commits/49e0b1460f5ae0485551886777d7dea95ff2073b
