### ISSUE TITLE
Event when the player drag a block

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#93]
Lorsque le joueur est en train de déplacer un bloc et qu'un event apparait, le joueur est obligé de le lâcher un peu à l'aveuglette. Il faudrait peut-être remettre le bloc là où il était, comme ça le joueur peut répondre à l'event et refaire sa manipulation.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/108/commits/d86f2f2a9e73590ec6fe1006522498ab8e7f55e2
