### ISSUE TITLE
Bridge on a Bridge

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#94]
On peut créer des ponts entre deux blocs déjà reliés par des ponts lorsque les blocs sont adjacents (sans cases entre ces deux blocs)
https://gyazo.com/a2c0e31d956bfce76cb424ad0fc988df

**Comment by Marolles** [comment]
Fixed in
https://github.com/Rackover/Stackolony/pull/108/commits/e75c4e8dd1de1c58d8e17618e03e1cc206a0ab23
