### ISSUE TITLE
Shift when the player have a block in hand

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#96]
Lorsque le joueur appuie sur Shift alors qu'il tient un bloc, ce block est figé, peu importe où il est, et on ne peut plus interagir avec lui. De plus, on ne peut plus faire de ponts à partir et vers ce block.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/108/commits/0e521526c163822c8012c79fb8488900a016a13b
