### ISSUE TITLE
Blocks override the menu

### ISSUE THREAD

**Issue by INoobody** [Rackover/Stackolony#97]
https://gyazo.com/167ebbe4e79120c47bb3a4a0249d5528

Les cases des blocs traversent le gris du menu, ces cases devraient passer sous le gris.

**Comment by Barkintosh** [comment]
Faut juste changer la hierarchy de l'interface et mettre le menu le plus en bas possible.

**Comment by Marolles** [comment]
Fixed in https://github.com/Rackover/Stackolony/pull/108/commits/dae70993f9ba39357507f85a71cfbdc3650bdacd
